name: Publish

on:
  workflow_dispatch:

env:
  MYUSER: ${{ vars.MYUSER }}
  MYEMAIL: ${{ vars.MYEMAIL }}
  MYPAT: ${{ secrets.MYPAT }}

jobs:

  publish:
    name: publish
    runs-on: macos-latest
    timeout-minutes: 90

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to MavenCentral
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
            ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
            ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
            ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
            ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
            ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

      - name: Github credentials
        uses: extractions/netrc@v1
        with:
          machine: github.com
          username: ${{ env.MYUSER }}
          password: ${{ env.MYPAT }}

      - name: Github config
        run: |
          git config --global user.name "${{ env.MYUSER }}"
          git config --global user.email "${{ env.MYEMAIL }}"

      - name: Create tag
        run: ./gradlew createTag
